# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: postgresql
 encoding: unicode
 database: <%= File.basename(Rails.root) %>_development
 pool: 5
 host: localhost
 template: template0

test:
 adapter: postgresql
 encoding: unicode
 database: <%= File.basename(Rails.root) %>_test
 pool: 5
 host: localhost
 template: template0

production:
 adapter: postgresql
 encoding: unicode
 database: <%= File.basename(Rails.root) %>_production
 pool: 5
 template: template0